#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$app = new Illuminate\Foundation\Application(
    realpath(__DIR__)
);

$app->singleton(
    Illuminate\Contracts\Debug\ExceptionHandler::class,
    App\Exceptions\Handler::class
);

$app->singleton(
    Symfony\Component\Console\Output\OutputInterface::class,
    Symfony\Component\Console\Output\ConsoleOutput::class
);

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(Luminee\Migrations\Kernel::class);

$status = $kernel->handle(
    $input = new Luminee\Migrations\Console\Supporters\Input,
    new Luminee\Migrations\Console\Supporters\Output($app)
);

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
|
| Once Artisan has finished running, we will fire off the shutdown events
| so that any final work may be done by the application before we shut
| down the process. This is the last thing to happen to the request.
|
*/

$kernel->terminate($input, $status);

exit($status);
